workflows:
  # Simple test workflow to debug issues
  ios-debug-workflow:
    name: iOS Debug Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "debug/*"
          include: true
          source: true
    scripts:
      - name: Environment check
        script: |
          echo "=== Environment Information ==="
          flutter --version
          xcodebuild -version
          echo "=== Directory structure ==="
          ls -la
      - name: Get dependencies
        script: flutter pub get
      - name: Flutter doctor
        script: flutter doctor -v
      - name: Build iOS (no code sign)
        script: |
          flutter build ios --release --no-codesign --verbose
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - colindiffer@gmail.com
        notify:
          success: true
          failure: true

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: HR5L39LBUF  # Using your Apple Developer Portal integration
    environment:
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.aareadingsandprayers.aaReadings25
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Set up environment
        script: |
          echo "Flutter version:"
          flutter --version
          echo "Xcode version:"
          xcodebuild -version
      - name: Get dependencies
        script: flutter pub get
      - name: Analyze
        script: flutter analyze
      - name: Test
        script: flutter test
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build IPA
        script: |
          flutter build ipa --release \
            --build-name=8.1.1 \
            --build-number=11 \
            --verbose
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - colindiffer@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration  # Uses the HR5L39LBUF integration configured in Codemagic
        submit_to_testflight: true
        submit_to_app_store: false
        # Note: App ID 6747896671 is configured in the App Store Connect integration

  # Simple test workflow to verify build works
  simple-test:
    name: Simple Test Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "test"
          include: true
          source: true
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build without signing
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - colindiffer@gmail.com
        notify:
          success: true
          failure: true
