workflows:
  ios-simulator-workflow:
    name: iOS Simulator Build & Run
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Flutter doctor
        script: flutter doctor -v
      - name: Check iOS setup
        script: |
          echo "=== iOS Simulator Information ==="
          xcrun simctl list devices available
          echo "=== Available Simulators ==="
          xcrun simctl list devices | grep "iPhone"
      - name: Start iOS Simulator
        script: |
          echo "=== Starting iOS Simulator ==="
          # Boot a simulator
          SIMULATOR_ID=$(xcrun simctl list devices | grep "iPhone 15" | grep -v "unavailable" | head -1 | grep -oE '\([A-F0-9-]+\)' | tr -d '()')
          if [ -z "$SIMULATOR_ID" ]; then
            SIMULATOR_ID=$(xcrun simctl list devices | grep "iPhone" | grep -v "unavailable" | head -1 | grep -oE '\([A-F0-9-]+\)' | tr -d '()')
          fi
          echo "Using simulator: $SIMULATOR_ID"
          xcrun simctl boot $SIMULATOR_ID || echo "Simulator may already be booted"
          sleep 5
      - name: Build and run in simulator
        script: |
          echo "=== Building and running app in simulator ==="
          # Build for simulator
          flutter build ios --debug --simulator --verbose
          
          echo "=== Installing app in simulator ==="
          # Install the app
          SIMULATOR_ID=$(xcrun simctl list devices | grep "iPhone" | grep "Booted" | head -1 | grep -oE '\([A-F0-9-]+\)' | tr -d '()')
          if [ -n "$SIMULATOR_ID" ]; then
            xcrun simctl install $SIMULATOR_ID build/ios/iphonesimulator/Runner.app
            echo "App installed successfully"
            
            echo "=== Launching app ==="
            # Launch the app and capture logs
            xcrun simctl launch $SIMULATOR_ID com.aareadingsandprayers.aaReadings25 &
            LAUNCH_PID=$!
            
            echo "App launched, waiting for 10 seconds to capture logs..."
            sleep 10
            
            echo "=== Capturing simulator logs ==="
            xcrun simctl spawn $SIMULATOR_ID log show --predicate 'process == "Runner"' --last 1m > simulator_logs.txt
            
            echo "=== App status ==="
            xcrun simctl list apps $SIMULATOR_ID | grep -i runner || echo "App not found in installed apps"
            
          else
            echo "❌ No booted simulator found"
          fi
      - name: Check app results
        script: |
          echo "=== Simulator Logs ==="
          if [ -f "simulator_logs.txt" ]; then
            echo "Last 50 lines of simulator logs:"
            tail -50 simulator_logs.txt
          else
            echo "No simulator logs found"
          fi
          
          echo "=== Build verification ==="
          if [ -d "build/ios/iphonesimulator/Runner.app" ]; then
            echo "✅ App built successfully"
            echo "App bundle contents:"
            ls -la build/ios/iphonesimulator/Runner.app/
            echo "Info.plist check:"
            plutil -p build/ios/iphonesimulator/Runner.app/Info.plist | head -10
          else
            echo "❌ App build failed"
          fi
    artifacts:
      - build/ios/iphonesimulator/Runner.app
      - simulator_logs.txt
    publishing:
      email:
        recipients:
          - colindiffer@gmail.com
        notify:
          success: true
          failure: true

  ios-debug-workflow:
    name: iOS Debug Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "debug/*"
          include: true
          source: true
    scripts:
      - name: Environment check
        script: |
          echo "=== Environment Information ==="
          flutter --version
          xcodebuild -version
          echo "=== Directory structure ==="
          ls -la
      - name: Get dependencies
        script: flutter pub get
      - name: Flutter doctor
        script: flutter doctor -v
      - name: Build iOS (no code sign)
        script: |
          flutter build ios --release --no-codesign --verbose
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - colindiffer@gmail.com
        notify:
          success: true
          failure: true

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: HR5L39LBUF
    environment:
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.aareadingsandprayers.aaReadings25
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Set up environment
        script: |
          echo "Flutter version:"
          flutter --version
          echo "Xcode version:"
          xcodebuild -version
      - name: Get dependencies
        script: flutter pub get
      - name: Analyze
        script: flutter analyze
      - name: Test
        script: flutter test
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build IPA
        script: |
          flutter build ipa --release \
            --build-name=8.1.1 \
            --build-number=11 \
            --verbose
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - colindiffer@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  simple-test:
    name: Simple Test Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "test"
          include: true
          source: true
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build without signing
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - colindiffer@gmail.com
        notify:
          success: true
          failure: true

  ios-debug-comprehensive:
    name: iOS Debug with Error Checking
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "ios-debug"
          include: true
          source: true
    scripts:
      - name: Environment check
        script: |
          echo "=== Environment Information ==="
          flutter --version
          flutter doctor -v
          xcodebuild -version
          echo "=== iOS Simulators ==="
          xcrun simctl list devices available
      - name: Get dependencies
        script: flutter pub get
      - name: Check pubspec and iOS config
        script: |
          echo "=== Pubspec.yaml version ==="
          cat pubspec.yaml | grep version
          echo "=== iOS Bundle ID ==="
          grep -A 5 -B 5 "PRODUCT_BUNDLE_IDENTIFIER" ios/Runner.xcodeproj/project.pbxproj || echo "Bundle ID not found"
          echo "=== iOS Info.plist ==="
          head -20 ios/Runner/Info.plist
      - name: Analyze code
        script: |
          flutter analyze --no-pub
      - name: Run tests
        script: |
          flutter test --no-pub || echo "Some tests failed, continuing..."
      - name: Check for iOS-specific issues
        script: |
          echo "=== Checking for common iOS issues ==="
          echo "Checking Firebase configuration..."
          if [ -f "ios/Runner/GoogleService-Info.plist" ]; then
            echo "✅ GoogleService-Info.plist found"
            echo "Checking if it has valid content..."
            grep -q "PROJECT_ID" ios/Runner/GoogleService-Info.plist && echo "✅ Firebase config looks valid" || echo "❌ Firebase config may be invalid"
          else
            echo "❌ GoogleService-Info.plist missing"
          fi
          echo "Checking permissions in Info.plist..."
          grep -q "NSMicrophoneUsageDescription" ios/Runner/Info.plist && echo "✅ Microphone permission found" || echo "❌ Microphone permission missing"
      - name: Build iOS with detailed logging
        script: |
          echo "=== Building iOS app ==="
          flutter build ios --debug --no-codesign --verbose 2>&1 | tee ios_build.log
          echo "=== Build completed ==="
      - name: Check build results
        script: |
          echo "=== Build Results ==="
          if [ -d "build/ios/iphoneos/Runner.app" ]; then
            echo "✅ iOS app built successfully"
            echo "App contents:"
            ls -la build/ios/iphoneos/Runner.app/
            echo "App size:"
            du -sh build/ios/iphoneos/Runner.app/
          else
            echo "❌ iOS app build failed"
            echo "Build directory contents:"
            ls -la build/ios/ || echo "Build directory doesn't exist"
          fi
    artifacts:
      - build/ios/iphoneos/Runner.app
      - ios_build.log
    publishing:
      email:
        recipients:
          - colindiffer@gmail.com
        notify:
          success: true
          failure: true

  ios-simulator-flutter-run:
    name: iOS Flutter Run Test
    instance_type: mac_mini_m2
    max_build_duration: 20
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Check available devices
        script: |
          echo "=== Available Flutter devices ==="
          flutter devices
      - name: Run app with timeout
        script: |
          echo "=== Running Flutter app with timeout ==="
          # Run the app for 30 seconds then capture output
          timeout 30 flutter run -d ios --verbose > flutter_run_output.txt 2>&1 || echo "Flutter run completed or timed out"
          echo "=== Flutter run output ==="
          cat flutter_run_output.txt
      - name: Analyze output
        script: |
          echo "=== Analyzing Flutter run results ==="
          if grep -q "Launching" flutter_run_output.txt; then
            echo "✅ App launched successfully"
          else
            echo "❌ App launch may have failed"
          fi
          
          if grep -q "error\|Error\|ERROR" flutter_run_output.txt; then
            echo "❌ Errors found in output:"
            grep -i error flutter_run_output.txt
          else
            echo "✅ No obvious errors found"
          fi
          
          if grep -q "exception\|Exception\|EXCEPTION" flutter_run_output.txt; then
            echo "❌ Exceptions found in output:"
            grep -i exception flutter_run_output.txt
          else
            echo "✅ No exceptions found"
          fi
    artifacts:
      - flutter_run_output.txt
    publishing:
      email:
        recipients:
          - colindiffer@gmail.com
        notify:
          success: true
          failure: true
