name: aa_readings_25
description: AA Daily Readings & Prayers
publish_to: 'none'
version: 8.1.2+11

environment:
  sdk: '^3.7.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_tts: ^4.0.2
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.4
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  in_app_review: ^2.0.9
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
